### ISSUE TITLE
No matching manifest for linux/arm/v7

### ISSUE THREAD

**Issue by porg** [hotio/qbittorrent#10]
- I used the docker compose template as presented on https://hotio.dev/containers/qbittorrent/#starting-the-container
  - Only variables I adapted was in the "volumes" section.
- Attempted a docker `pull`
  - It fails with:` bittorrent Pulling no matching manifest for linux/arm/v7 in the manifest list entries`
- Then changed
  - from: `image: cr.hotio.dev/hotio/qbittorrent`
  - to: `image: cr.hotio.dev/hotio/qbittorrent:release-4.4.3.1` in the hopes this may contain the arm compiled version
  - also no luck

## Environment
- OpenMediaVault 6 (Debian 11)
- Armbian 22.05.3 Bullseye with Linux 5.4.199-odroidxu4
- On an Odroid-HC2 NAS (ARM 32bit CPU)

**Comment by mrhotio** [comment]
correct, only arm64 is supported
