### ISSUE TITLE
Warning: Extension CONNMARK revision 0 not supported, missing kernel module

### ISSUE THREAD

**Issue by nickgreen43** [hotio/qbittorrent#11]
Is this due to me trying to run this in a Windows Docker host?

**qbittorrent    | Warning: Extension CONNMARK revision 0 not supported, missing kernel module?**
qbittorrent    | iptables-restore: line 7 failed
qbittorrent    | [#] resolvconf -d wg0 -f
qbittorrent    | [#] ip -4 rule delete table 51820
qbittorrent    | [#] ip -4 rule delete table main suppress_prefixlength 0
qbittorrent    | [#] ip link delete dev wg0
**qbittorrent    | [ERROR] WireGuard failed to start.**
qbittorrent    | [cont-init.d] 02-setup-wg: exited 1.
qbittorrent    | [cont-finish.d] executing container finish scripts...
qbittorrent    | [cont-finish.d] 01-kill-wg: executing...
qbittorrent    | [cont-finish.d] 01-kill-wg: exited 0.
qbittorrent    | [cont-finish.d] done.
qbittorrent    | [s6-finish] waiting for services.
qbittorrent    | [s6-finish] sending all processes the TERM signal.
qbittorrent    | [s6-finish] sending all processes the KILL signal and exiting.
qbittorrent exited with code 1

**Comment by mrhotio** [comment]
most likely, please use the dicord for these types of support questions

**Comment by SolomonHD** [comment]
@nickgreen43 If you're still having this issue you must recompile the WSL2 kernel from Microsoft with the following options enabled:

```
CONFIG_NETFILTER_XT_MATCH_CONNMARK=y
CONFIG_NETFILTER_XT_CONNMARK=y
CONFIG_IPV6_MULTIPLE_TABLES=y
CONFIG_IPV6_SUBTREES=n
CONFIG_NET_VRF=n
```
Last 3 are for IPv6

**Comment by Celarye** [comment]
@SolomonHD's solution did fix this for me, but I'm wondering how to keep my kernel up to date with this? Should I write a cron job or do this manually from time to time?
