### ISSUE TITLE
[Feature] ENV Variable to change the IP service used

### ISSUE THREAD

**Issue by Belphemur** [hotio/qbittorrent#13]
Hello,

I'm having some issues where `icanhazip.com` don't answer the query (I'm thinking they surely block some VPN provider or have too many requests sent to them).

I've set `VPN_IP_CHECK_EXIT=true` to not stop the container from starting.

But it'd be nice if I could use a env var to override the service to use (like using `ifconfig.co` or `ifconfig.me` or anything else as long as it return the IP in clear text).

I'm suggesting a env var like: `VPN_IP_CHECK_SERVICE` that could be set to any website.

Btw, if you're interested, I can make a PR for it.

**Comment by jyggen** [comment]
Seeing this too, most of the time when the container starts icanhazip.com simply returns nothing no matter how long of a delay is added before the IP check.

**Comment by mrhotio** [comment]
I'd like to not make this a configurable option with a bunch of choices, let's just pick an alternative that works....what about `dig -4 TXT +short whoami.cloudflare @1.1.1.1 ch 2>/dev/null | tr -d '"'`?

**Comment by jyggen** [comment]
Works for me!

**Comment by mrhotio** [comment]
ok, test the new release

**Comment by jyggen** [comment]
The container exits with the following error message:
```
[ERROR] ipv6 is disabled, but we got data back in our ipv6 lookup. Exiting...
```

**Comment by mrhotio** [comment]
Test new update

**Comment by mrhotio** [comment]
Not for people using mullvad it seems…might still have to tweak this.

**Comment by Nocifer** [comment]
Hello, any word on this one getting fixed? It really does not like Mullvad, so we've been stuck on `release-64adf7b` for a while now :)

**Comment by mrhotio** [comment]
The check is completely removed, so it can’t cause you an issue.
