### ISSUE TITLE
qbittorrent starts, but can't connect to any peers/seeds

### ISSUE THREAD

**Issue by glassman81** [hotio/qbittorrent#14]
When running qbittorrent, I place the wg0.conf in the appropriate location, and I can access the WebUI, but I can never seem to connect to any peers, despite using multiple torrent files with many seeders.

Here is my configuration:

docker run --name qbittorrent-wireguard_pia -d \
              -v /mnt/fileserver/downloads:/mnt/fileserver/downloads \
              -v /mnt/docker/config/qbittorrent/:/config \
              -p 8080:8080 \
              -p 8118:8118 \
              -e TZ="Etc/UTC" \
              -e VPN_ENABLED="true" \
              -e VPN_LAN_NETWORK="10.10.10.0/24" \
              -e VPN_CONF="wg0" \
              -e VPN_ADDITIONAL_PORTS="" \
              -e PRIVOXY_ENABLED="false" \
              -e PUID=1000 \
              -e PGID=1000 \
              -e UMASK=002 \
              --device=/dev/net/tun:/dev/net/tun \
              --cap-add NET_ADMIN \
              --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
              --sysctl="net.ipv6.conf.all.disable_ipv6=0" \
              --restart unless-stopped \
              cr.hotio.dev/hotio/qbittorrent

The following is the log output captured from the console:

----------------------------------------------------------------------

0

0

2
TZ=Etc/UTC
WEBUI_PORTS=8080/tcp,8080/udp
VPN_ENABLED=true
VPN_LAN_NETWORK=10.10.10.0/24

VPN_CONF=wg0
VPN_ADDITIONAL_PORTS=
PRIVOXY_ENABLED=false
----------------------------------------------------------------------
Executing usermod...
usermod: no changes
Applying permissions to /config
cont-init: info: /etc/cont-init.d/00-start-container exited 0
cont-init: info: running /etc/cont-init.d/01-configure-app
cont-init: info: /etc/cont-init.d/01-configure-app exited 0
cont-init: info: running /etc/cont-init.d/02-setup-wg
[INFO] Docker network type is not set to "host".
[INFO] "sysctl net.ipv4.conf.all.src_valid_mark=1" is set.
[INFO] Configuration file "/config/wireguard/wg0.conf" was found.
[INFO] WireGuard is down. Continuing...
[INFO] Starting WireGuard...
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.183.131 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] ip -4 route add 128.0.0.0/1 dev wg0
[#] ip -4 route add 0.0.0.0/1 dev wg0
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
skipping setting net.ipv4.conf.all.src_valid_mark
[#] echo skipping setting net.ipv4.conf.all.src_valid_mark
[#] iptables-restore -n
[#] wg set wg0 fwmark 51820 && ip -4 rule add not fwmark 51820 table 51820 && ip -4 rule add table main suppress_prefixlength 0 && iptables-restore -n
[INFO] WireGuard is started.
[INFO] WebUI ports are "8080/tcp,8080/udp".
[INFO] Additional ports are "".
[INFO] WireGuard remote is "84.17.45.9:1337".
[INFO] Docker network interface is "eth0".
[INFO] Docker network IP is "172.17.0.13".
[INFO] Docker network CIDR is "172.17.0.0/16".
[INFO] Adding "10.10.10.0/24" as route via interface "eth0".
[INFO] ip route overview:
0.0.0.0/1 dev wg0 scope link 
default via 172.17.0.1 dev eth0 
10.10.10.0/24 via 172.17.0.1 dev eth0 
128.0.0.0/1 dev wg0 scope link 
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.13 
[INFO] Configuring iptables...
[INFO] Configuring ip6tables...
[INFO] iptables overview:
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -i wg0 -p udp -m udp --dport 8080 -j DROP
-A INPUT -i wg0 -p tcp -m tcp --dport 8080 -j DROP
-A INPUT -i wg0 -p udp -j ACCEPT
-A INPUT -i wg0 -p tcp -j ACCEPT
-A INPUT -s 172.17.0.0/16 -d 172.17.0.0/16 -j ACCEPT
-A INPUT -i eth0 -p udp -m udp --sport 1337 -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -i eth0 -p udp -m udp --dport 8080 -j ACCEPT
-A OUTPUT -o wg0 -p udp -m udp --sport 8080 -j DROP
-A OUTPUT -o wg0 -p tcp -m tcp --sport 8080 -j DROP
-A OUTPUT -o wg0 -p udp -j ACCEPT
-A OUTPUT -o wg0 -p tcp -j ACCEPT
-A OUTPUT -s 172.17.0.0/16 -d 172.17.0.0/16 -j ACCEPT
-A OUTPUT -o eth0 -p udp -m udp --dport 1337 -j ACCEPT
-A OUTPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --sport 8080 -j ACCEPT
-A OUTPUT -o eth0 -p udp -m udp --sport 8080 -j ACCEPT
[INFO] ip6tables overview:
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -i wg0 -p udp -m udp --dport 8080 -j DROP
-A INPUT -i wg0 -p tcp -m tcp --dport 8080 -j DROP
-A INPUT -i wg0 -p udp -j ACCEPT
-A INPUT -i wg0 -p tcp -j ACCEPT
-A OUTPUT -o wg0 -p udp -m udp --sport 8080 -j DROP
-A OUTPUT -o wg0 -p tcp -m tcp --sport 8080 -j DROP
-A OUTPUT -o wg0 -p udp -j ACCEPT
-A OUTPUT -o wg0 -p tcp -j ACCEPT
cont-init: info: /etc/cont-init.d/02-setup-wg exited 0
cont-init: info: running /etc/cont-init.d/03-setup-privoxy
cont-init: info: /etc/cont-init.d/03-setup-privoxy exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun qbittorrent (no readiness notification)
s6-rc: info: service legacy-services successfully started
WebUI will be started shortly after internal preparations. Please wait...

I don't know exactly what's happening because I can't find any more relevant logs, but the only indication that I see that something may be wrong the last line that says "WebUI will be started shortly after internal preparations. Please wait...". It seems to be stuck there?

**Comment by mrhotio** [comment]
Use the discord for support

**Comment by ASOwnerYT** [comment]
I have the same issue, stuck on "WebUI will be started shortly after internal preparations. Please wait..."

**Comment by seventhsite** [comment]
Any news for those who don't use discord?
I can ping from container, DNS is working, but any added torrent can't connect to any tracker.

**Comment by mrhotio** [comment]
that error message is irrelevant, it's most likely bad config
