### ISSUE TITLE
When the VPN is enabled, the container is unable to resolve other docker containers

### ISSUE THREAD

**Issue by ColinHebert** [hotio/qbittorrent#15]
As it's set right now, when the VPN is enabled, the iptables rules are set in such a way that the local DNS server (in docker) is not reachable.
This is more often than not "fine" as the container can use the DNS associated with the VPN connection. Unfortunately, when the system is set up this way, it becomes impossible to resolve the address of other docker containers in the network.

For example it is not possible to connect the qbittorrent container to a cross-seed container locally.

A way to work around that is to allow the connection to the local DNS server, or simply reach out to port 53:
```
echo "Allow DNS resolution locally"
iptables -A INPUT -i eth0 -p udp -m udp --sport 53 -j ACCEPT
iptables -A OUTPUT -o eth0 -p udp -m udp --dport 53 -j ACCEPT
```

This can be done in smarter ways, for example detecting which network interface should be picked (the one for the default route for example).

With this addintion to the iptables, and if the DNS server is disabled in the wireguard configuration, qBIttorrent will be able to reach out to other containers within its network.

**Comment by mrhotio** [comment]
I was trying to add this, but it seems that local dns resolution of container names just works if we don't let wireguard overwrite resolv.conf, which seems to be not working anymore since recently...

**Comment by pwsnla** [comment]
I just wanted to chime in because as far as I am concerned nothing is broken.
I use this container and local name resolution (using container names) always worked for me and it still works as long as I don't override DNS server in wireguard config. This is out of the box setup on Ubuntu 22.04 without any tweaks so I am not sure what's different about OPs set up.
