### ISSUE TITLE
Can no longer specify exact version to pull other than fixed legacy and latest.

### ISSUE THREAD

**Issue by Flute7** [hotio/qbittorrent#20]
It used to be possible to specify "image: cr.hotio.dev/hotio/qbittorrent:release-4.5.4" in a docker command to pull a specific version.
This now results in manifest unknown because only fixed legacy and latest version tags are available.

Other related software like qBitManage is sometimes a release behind and occasionally requires a specific qBittorrent version. Jumping back using a tag was pretty handy.

Can this functionality be added back? I have no idea of the required work or consequences of this request.

**Comment by mrhotio** [comment]
Pull straight from dockerhub, been asked and answered numerous times in the correct channels…

**Comment by Flute7** [comment]
Thanks. Perhaps I am naive, what are the 'correct' channels so I don't ask the wrong question in the wrong place again?

**Comment by mrhotio** [comment]
Yep discord it is, github issues is for reporting an issue with the image if you lack the knowledge to file a pull request
