### ISSUE TITLE
s6-rc: fatal: unable to take locks: Resource busy

### ISSUE THREAD

**Issue by ClementNerma** [hotio/qbittorrent#24]
Hi!

I'm trying to run this image, but getting the following error:

```
s6-rc: fatal: unable to take locks: Resource busy
```

I also get later:

```
modprobe: can't change directory to '/lib/modules': No such file or directory
```

I can't figure out why :/

Do you have any idea why this happens?

Running on Ubuntu 23.04 on an x86 machine.

**Comment by mrhotio** [comment]
Use discord for support and provide logs
