### ISSUE TITLE
Port Forwarding Warning

### ISSUE THREAD

**Issue by aaronmee** [hotio/qbittorrent#34]
Hi,
I set up a docker compose container using this image to hide qbittorrent behind my wireguard vpn. The port forwarding seems to work as my client is connectable, but in the docker logs I can see an error that doesn't seem to impact functionality:
```
[INF] [2024-05-21 10:50:06] [VPN] Forwarded port is [45598].
Error: syntax error, unexpected colon
add rule inet hotio prerouting iifname wg0 true dport 45598 redirect to :true
                                                                        ^
[INF] [2024-05-21 10:50:06] [VPN] Redirected port [45598/true] to [true/true].
[INF] [2024-05-21 10:50:06] [QBITTORRENT] Updated forwarded port to [45598].
```

The client, web ui and downloads work as expected so maybe an unimportant issue here

**Comment by mrhotio** [comment]
Use discord for support, read the rules….This is definitely not ok.

**Comment by aaronmee** [comment]
Wasn't meant as support but as bug report, but ok 👍

**Comment by mrhotio** [comment]
You’re feeding it wrong data… that’s why you are seeing that.

**Comment by aaronmee** [comment]
Where could I possibly feed wrong data that causes this? It looks more like some internal logic to me

**Comment by mrhotio** [comment]
In your docker command/compose
