### ISSUE TITLE
Firewall in docker blocking incoming connections to utorrent? 

### ISSUE THREAD

**Issue by mdarkice** [hotio/qbittorrent#35]
Problem with portforward to utorrent after update. it seems like the ports i try to use in my portforward to utorrent doesnt work after last update.. i tried changing ports even same result. any issues with the new release? like firewall blocking incoming requests?

/br Kim

**Comment by mrhotio** [comment]
There's no utorrent in the image....there's also no "new" update....and this is NOT the place for support...
