### ISSUE TITLE
Edit VueTorrent version

### ISSUE THREAD

**Issue by HDebeuf** [hotio/qbittorrent#4]
Dear hotio,

You did an amazing job on this container!
I was wondering if for the next update, you could consider [VueTorrent v0.11.0](https://github.com/WDaan/VueTorrent/releases/tag/v0.11.0).

Otherwise, is there any way to add this with an environment variable?

Thank you.

Best regardsn

**Comment by mrhotio** [comment]
That version should be in there...it auto updates, see git commits
